name: Docker Image CI

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fildzaanf:latest
      -
        name: connect ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo docker stop ${{ secrets.CNAME }}
            sudo docker rm ${{ secrets.CNAME }}
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/fildzaanf
            sudo docker run --name ${{ secrets.CNAME }} -p 8000:8000 -d \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e SMTP_EMAIL=${{ secrets.SMTP_EMAIL }} \
            -e SMTP_HOST=${{ secrets.SMTP_HOST }} \
            -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
            -e SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
            -e PORT=${{ secrets.PORT }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/fildzaanf
