name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fildzaanf:latest

      - name: Connect via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo docker stop ${{ secrets.CNAME }} || true
            sudo docker rm ${{ secrets.CNAME }} || true
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/fildzaanf || true
            sudo docker run --name ${{ secrets.CNAME }} -p 8000:8000 -d \
              -e POSTGRESQL_HOST=${{ secrets.POSTGRESQL_HOST }} \
              -e POSTGRESQL_PORT=${{ secrets.POSTGRESQL_PORT }} \
              -e POSTGRESQL_USER=${{ secrets.POSTGRESQL_USER }} \
              -e POSTGRESQL_PASS=${{ secrets.POSTGRESQL_PASS }} \
              -e POSTGRESQL_NAME=${{ secrets.POSTGRESQL_NAME }} \
              -e SMTP_EMAIL=${{ secrets.SMTP_EMAIL }} \
              -e SMTP_HOST=${{ secrets.SMTP_HOST }} \
              -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
              -e SMTP_PASS=${{ secrets.SMTP_PASS }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e PORT=${{ secrets.PORT }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/fildzaanf
